

# This file was *autogenerated* from the file conversions.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_4 = Integer(4)
import drawing

def cycles_to_two_row(n, cycle_string, signed=True):
	"""Converts a cycle notation string into two-row notation"""
	# Example: '(1,-2,3)(1,-1)(3,-4)'
	cycles = list(reversed(list(map(lambda cycle: (cycle.replace('(','').replace(')','')).split(','), cycle_string.split(')(')))))
	G = SymmetricGroup(_sage_const_3 )
	ans = dict()
	for cycle in cycles:
		print(cycle)
	
cycles_to_two_row(_sage_const_4 , '(1,-2,-4)(1,-1)(3,-4)')

